sudo: false
language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
env:
  - TEST=1
  - TYPECHECK=1
  - LINT=1

script:
  - ./config/travis/test.sh
before_install: npm install react react-dom prop-types && npm install
after_success: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
